//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LouisianaManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLY_LOUISIANAEntities : DbContext
    {
        public QUANLY_LOUISIANAEntities()
            : base("name=QUANLY_LOUISIANAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<INPUT> INPUTs { get; set; }
        public virtual DbSet<INPUTINFO> INPUTINFOes { get; set; }
        public virtual DbSet<OBJECT> OBJECTs { get; set; }
        public virtual DbSet<OUTPUT> OUTPUTs { get; set; }
        public virtual DbSet<OUTPUTINFO> OUTPUTINFOes { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<UNIT> UNITs { get; set; }
        public virtual DbSet<USERROLE> USERROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
